# Generated by Django 5.2.1 on 2025-05-30 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Permit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=20, unique=True)),
                ("event_type", models.CharField(max_length=100)),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                ("parking_held", models.TextField(blank=True)),
                ("borough", models.CharField(max_length=50)),
                ("community_boards", models.CharField(blank=True, max_length=100)),
                ("category", models.CharField(max_length=100)),
                ("subcategory", models.CharField(max_length=100)),
                ("zip_codes", models.CharField(max_length=100)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lon", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
