# Generated by Django 5.2.1 on 2026-03-07 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permit",
            name="borough",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="permit",
            name="category",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="permit",
            name="community_boards",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="permit",
            name="subcategory",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="permit",
            name="zip_codes",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="PermitBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("block_order", models.IntegerField()),
                ("raw_location", models.TextField()),
                ("on_street", models.CharField(blank=True, max_length=255)),
                ("cross_street_one", models.CharField(blank=True, max_length=255)),
                ("cross_street_two", models.CharField(blank=True, max_length=255)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lon", models.FloatField(blank=True, null=True)),
                ("geocode_status", models.CharField(blank=True, max_length=50)),
                (
                    "permit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="permits.permit",
                    ),
                ),
            ],
        ),
    ]
