# Generated by Django 5.2.1 on 2026-03-07 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permits", "0002_alter_permit_borough_alter_permit_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="permitblock",
            name="borough",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
