# Generated by Django 5.2.1 on 2026-03-11 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permits", "0003_permitblock_borough"),
    ]

    operations = [
        migrations.CreateModel(
            name="StreetSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("segment_id", models.CharField(max_length=50, unique=True)),
                ("street", models.CharField(blank=True, max_length=255)),
                ("borough", models.CharField(blank=True, max_length=50)),
                ("geometry_geojson", models.JSONField()),
                ("permit_count", models.IntegerField(default=0)),
            ],
        ),
    ]
