# Generated by Django 5.2.1 on 2026-03-11 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permits", "0004_streetsegment"),
    ]

    operations = [
        migrations.AddField(
            model_name="permitblock",
            name="segment_id",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="permitblock",
            name="segment_match_status",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
